### ISSUE TITLE
Get data from the row in PurityReportList

### ISSUE THREAD

**Issue by claude-peon** [gnu-team/canteen-app#33]
We need to get the data (coords in this case) from the row and then look at at the history of this point in graph form.

-Need to get coords
-IF the manager selects virus- Y-axis is Virus PPM
-IF the manager selects contaminant- Y-axis is Contaminant PPM
-IF there was no test during a month- there is no data point

**Comment by ausbin** [comment]
45f1948ac8c8c1e0b6eae704c23863227074b3de
